### PR TITLE
fix: FilterStorage URL encoding

### LINKED ISSUE #697: bug: FilterStorage values with spaces not properly percent encoded
**Describe the bug 🐛**

In case of multi-index search, the queries are sent being URL-encoded.
The URL-encoded `FiltersStorage` structure representing query filter fields using legacy syntax don't have values of filters wrapped in quotation marks, so if the value of a filter (e.g facet name) includes spaces, the search engine rejects the search request due to wrong encoding.  

**Expected behavior 💭**

The value of filters are wrapped in quotation marks, so the potential spaces are properly encoded and the engine accepts the multi-index request.

**Additional context**
Related [Helpscout ticket](https://secure.helpscout.net/conversation/1336157634).

### PR DESCRIPTION
**Pull request by VladislavFitz**
**Summary**

Fixes #697

### CODE REVIEW

File: Sources/AlgoliaSearchClient/Models/Search/Query/Query+URLEncodable.swift [hunk 1]
```diff
@@ -12,7 +12,10 @@ extension Query {
   struct URLEncoder<Key: RawRepresentable> where Key.RawValue == String {
 
     var queryItems: [URLQueryItem] = []
-
+    
+    func wrapInQuotes(_ input: String) -> String { "\"\(input)\"" }
+    func wrapInBrackets(_ input: String) -> String { "[\(input)]" }
```
Comment (spinach) [inline Sources/AlgoliaSearchClient/Models/Search/Query/Query+URLEncodable.swift:17]: Maybe better to put it as a `String` extension?

**Review by spinach — APPROVED** [review]
